export const ENUM = {
  PRODUCT: {
    AVAILABLE_FOR: { SELL: 'sell', RENT: 'rent', DONATE: 'donate' },
    STATUS: { ACTIVE: 'active', DELETE: 'delete', IN_ACTIVE: 'inactive' },
    CATEGORY: {
      BOOKS: 'books',
      ELECTRONICS: 'electronics',
      CLOTHING: 'clothing',
      GROCERIES: 'groceries',
    },
    CATEGORY_STATUS: {
      ACTIVE: 'active',
      DELETE: 'delete',
      IN_ACTIVE: 'inactive',
    },
  },
  SUBSCRIPTION: {
    // ["Daily", "Weekly", "Monthly", "Quarterly", "Yearly", "Custom"]
    FREQUENCY: {
      DAILY: 'Daily',
      WEEKLY: 'Weekly',
      MONTHLY: 'Monthly',
      QUARTERLY: 'Quarterly',
      YEARLY: 'Yearly',
      CUSTOM: 'Custom',
    },
    FREQUENCY_DETAILS: {
      // ["Weekly", "Monthly", "Interval"]

      WEEKLY: 'Weekly',
      MONTHLY: 'Monthly',
      YEARLY: 'Yearly',
      INTERVAL: 'Interval',
    },
  },
  ORDER: {
    STATUS: {
      PENDING: 'pending',
      COMPLETED: 'completed',
      CANCELLED: 'cancelled',
      RETURNED: 'returned',
      FAILED: 'failed',
    },
    TYPE: {
      PURCHASE: 'purchase',
      RENTAL: 'rental',
      SUBSCRIPTION: 'subscription',
    },
    PAYMENT_STATUS: {
      UNPAID: 'unpaid',
      PAID: 'paid',
      REFUNDED: 'refunded',
      PARTIAL: 'partial',
    },
    DELIVERY_STATUS: {
      PENDING: 'pending',
      ON_ROUTE: 'on-route',
      DELIVERED: 'delivered',
      FAILED: 'failed',
    },
  },
  COL: {
    ACTIVITY: 'activities',
    JOBLISTING: 'joblistings',
    USER: 'user',
    JOBSEEKER: 'jobseeker',
    JOBPROVIDER: 'jobprovider',
    MATCHMAKING: 'matchmaking',
    SERVICE: 'service',
    SERVICEPROVIDER: 'serviceprovider',
    REVIEW: 'reviews',
    MESSAGE: 'messages',
    PREFERENCE: 'preferences',
    DEVICE_DETAILS: 'device_details',
    NOTIFICATION: 'notifications',
  },
  USER: {
    ROLE: {
      CUSTOMER: 'customer',
      MERCHANT: 'merchant',
      DELIVERY: 'delivery',
    },
    ADDRESS_TYPE: {
      HOME: 'Home',
      WORK: 'Work',
      OTHER: 'Other',
    },
    LANG: {
      // "af": "Afrikaans",
      //   am: "Amharic",
      ar: 'Arabic',
      //   az: "Azerbaijani",
      //   be: "Belarusian",
      //   bg: "Bulgarian",
      bn: 'Bengali',
      //   bs: "Bosnian",
      //   ca: "Catalan",
      //   ceb: "Cebuano",
      //   co: "Corsican",
      //   cs: "Czech",
      //   cy: "Welsh",
      //   da: "Danish",
      de: 'German',
      //   el: "Greek",
      en: 'English',
      //   eo: "Esperanto",
      es: 'Spanish',
      //   et: "Estonian",
      //   eu: "Basque",
      //   fa: "Persian",
      //   fi: "Finnish",
      //   fr: "French",
      //   fy: "Frisian",
      //   ga: "Irish",
      //   gd: "Scots Gaelic",
      //   gl: "Galician",
      gu: 'Gujarati',
      //   ha: "Hausa",
      //   haw: "Hawaiian",
      //   he: "Hebrew",
      //   hi: "Hindi",
      //   hmn: "Hmong",
      //   hr: "Croatian",
      //   ht: "Haitian Creole",
      //   hu: "Hungarian",
      //   hy: "Armenian",
      //   id: "Indonesian",
      //   ig: "Igbo",
      //   is: "Icelandic",
      //   it: "Italian",
      ja: 'Japanese',
      //   jv: "Javanese",
      //   ka: "Georgian",
      //   kk: "Kazakh",
      //   km: "Khmer",
      kn: 'Kannada',
      ko: 'Korean',
      //   ku: "Kurdish (Kurmanji)",
      //   ky: "Kyrgyz",
      //   la: "Latin",
      //   lb: "Luxembourgish",
      //   lo: "Lao",
      //   lt: "Lithuanian",
      //   lv: "Latvian",
      //   mg: "Malagasy",
      //   mi: "Maori",
      //   mk: "Macedonian",
      //   ml: "Malayalam",
      //   mn: "Mongolian",
      mr: 'Marathi',
      //   ms: "Malay",
      //   mt: "Maltese",
      //   my: "Myanmar (Burmese)",
      //   ne: "Nepali",
      //   nl: "Dutch",
      //   no: "Norwegian",
      //   ny: "Chichewa",
      //   or: "Odia (Oriya)",
      //   pa: "Punjabi",
      //   pl: "Polish",
      //   ps: "Pashto",
      //   pt: "Portuguese",
      //   ro: "Romanian",
      ru: 'Russian',
      sd: 'Sindhi',
      //   si: "Sinhala",
      //   sk: "Slovak",
      //   sl: "Slovenian",
      //   sm: "Samoan",
      //   sn: "Shona",
      //   so: "Somali",
      //   sq: "Albanian",
      //   sr: "Serbian",
      //   st: "Sesotho",
      //   su: "Sundanese",
      //   sv: "Swedish",
      //   sw: "Swahili",
      ta: 'Tamil',
      te: 'Telugu',
      //   tg: "Tajik",
      //   th: "Thai",
      //   tr: "Turkish",
      //   uk: "Ukrainian",
      ur: 'Urdu',
      //   uz: "Uzbek",
      //   vi: "Vietnamese",
      //   xh: "Xhosa",
      //   yi: "Yiddish",
      //   yo: "Yoruba",
    },
  },
  BUSINESS: {
    TYPE: {
      RESTAURANT: 'Restaurant',
      RETAIL: 'Retail',
      SERVICES: 'Services',
      MANUFACTURING: 'Manufacturing',
      FOOD_BEVERAGE: 'Food & Beverage',
      TECHNOLOGY: 'Technology',
      HEALTHCARE: 'Healthcare',
      EDUCATION: 'Education',
      OTHER: 'Other',
    },
  },
};

export const ENUM_ARRAY = {
  PRODUCT: {
    AVAILABLE_FOR: Object.values(ENUM.PRODUCT.AVAILABLE_FOR),
    STATUS: Object.values(ENUM.PRODUCT.STATUS),
    CATEGORY: Object.values(ENUM.PRODUCT.CATEGORY),
    CATEGORY_STATUS: Object.values(ENUM.PRODUCT.STATUS),
  },
  SUBSCRIPTION: {
    FREQUENCY: Object.values(ENUM.SUBSCRIPTION.FREQUENCY),
    FREQUENCY_DETAILS: Object.values(ENUM.SUBSCRIPTION.FREQUENCY_DETAILS),
  },
  USER: {
    ROLE: Object.values(ENUM.USER.ROLE),
    ADDRESS_TYPE: Object.values(ENUM.USER.ADDRESS_TYPE),
    LANG: Object.values(ENUM.USER.LANG),
  },
  ORDER: {
    STATUS: Object.values(ENUM.ORDER.STATUS),
    TYPE: Object.values(ENUM.ORDER.TYPE),
    PAYMENT_STATUS: Object.values(ENUM.ORDER.PAYMENT_STATUS),
    DELIVERY_STATUS: Object.values(ENUM.ORDER.DELIVERY_STATUS),
  },
  BUSINESS: {
    TYPE: Object.values(ENUM.BUSINESS.TYPE),
  },
  BOOKMARK: {},
};
